services:
  - type: web
    name: hostel-backend
    env: node
    buildCommand: "npm install"
    startCommand: "node server.js"
    envVars:
      - key: MONGODB_URI
        sync: false
      - key: PORT
        value: 5000
